// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRhebK0Y0Ev1ipyxRbRq6GeKjTzj_VrE',
    appId: '1:43347560927:android:88bbfdcb919d8d27cc9c6a',
    messagingSenderId: '43347560927',
    projectId: 'clothesesshop',
    databaseURL: 'https://clothesesshop-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clothesesshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaPcwk2oGFU76W6aYXS_vZsZ9f2NB39Ws',
    appId: '1:43347560927:ios:429d6243d4704cd8cc9c6a',
    messagingSenderId: '43347560927',
    projectId: 'clothesesshop',
    databaseURL: 'https://clothesesshop-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clothesesshop.appspot.com',
    iosBundleId: 'dev.erkinov.clothesesShop',
  );
}
